# scripts/update_readme.py
"""Rewrite the results section of README.md from the generated files.

Three different 68% credibility intervals for kappa were in circulation --
manuscript [1.26, 1.64], fit_results.json [1.247, 1.640], README [1.249,
1.629] -- because each was typed by hand from a different unseeded run.

Numbers quoted in the README are now generated. The block between the two
markers below is replaced wholesale; edit anything outside it freely.
"""
from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
README = REPO_ROOT / "README.md"
RESULTS_DIR = REPO_ROOT / "results"

START = "<!-- BEGIN GENERATED RESULTS -->"
END = "<!-- END GENERATED RESULTS -->"


def render() -> str:
    with open(RESULTS_DIR / "fit_results.json") as fh:
        fit = json.load(fh)
    with open(RESULTS_DIR / "global_consistency.json") as fh:
        consistency = json.load(fh)

    models = fit["models"]
    posterior = fit["posterior"]
    significance = fit["significance"]
    comparisons = fit["comparisons"]
    provenance = fit["provenance"]

    lines = [
        START,
        "",
        "### Model comparison",
        "",
        "| model | params | chi2 | dof | p(gof) | AIC | best fit |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for name, entry in models.items():
        best = ", ".join(f"{v:+.3f}" for v in entry["best_fit"]) or "—"
        lines.append(
            f"| {name} | {entry['n_params']} | {entry['chi2']:.2f} | "
            f"{entry['dof']} | {entry['p_goodness_of_fit']:.3f} | "
            f"{entry['aic']:.2f} | {best} |"
        )

    kappa_lo = posterior["kappa_median"] - posterior["kappa_lower"]
    kappa_hi = posterior["kappa_upper"] - posterior["kappa_median"]

    lines += [
        "",
        "### Headline numbers",
        "",
        f"- **kappa = {posterior['kappa_median']:+.2f} "
        f"(+{kappa_hi:.2f} / −{kappa_lo:.2f})** at 68% credibility.",
        f"- **chi2_SM = {models['SM']['chi2']:.2f}** for {models['SM']['dof']} dof "
        f"(p = {models['SM']['p_goodness_of_fit']:.3f}).",
        f"- **Significance {significance['significance_toys']:.2f} sigma**, "
        f"calibrated with {significance['n_toys']} SM pseudo-experiments "
        f"(p = {significance['p_value_toys']:.4f}). The naive "
        f"sqrt(delta chi2) would give "
        f"{significance['significance_wilks_naive']:.2f}.",
        f"- Against a free constant Delta C9 at equal parameter count, the USF "
        f"gains **delta chi2 = {comparisons['delta_chi2_c9_minus_usf']:+.3f}** — "
        "that is, nothing.",
        f"- Freeing the f_geo amplitude buys "
        f"{comparisons['delta_chi2_usf_minus_ansatz']:+.3f} in chi2 for one "
        f"extra parameter, so AIC worsens from "
        f"{models['USF (kappa)']['aic']:.2f} to "
        f"{models['USF ansatz (kappa, A)']['aic']:.2f}.",
        "",
        "### Cross-check against other b → s ℓℓ observables",
        "",
        f"Testing the framework's fixed prediction "
        f"Delta C10 = {consistency['c10_over_c9']} × Delta C9 at "
        f"Delta C9 = {consistency['delta_c9']:+.3f}:",
        "",
        "| scenario | sum of squared pulls | worst tension |",
        "| --- | ---: | --- |",
        f"| Standard Model | {consistency['sum_squared_pulls_sm']:.2f} | — |",
    ]
    for name, entry in consistency["scenarios"].items():
        lines.append(
            f"| {name} | {entry['sum_squared_pulls_usf']:.2f} | "
            f"{entry['worst_observable']} at {entry['worst_pull']:+.2f} sigma |"
        )

    lines += [
        "",
        "The verdict depends on whether the geometric modification is lepton "
        "universal, which the manuscript never states. A muon-specific shift of "
        "this size is excluded by R_K; a lepton-universal one — the natural "
        "reading for an effect sourced by spacetime geometry — survives.",
        "",
        "### Provenance",
        "",
        f"- Seed `{provenance['seed']}`, {provenance['n_walkers']} walkers × "
        f"{provenance['n_steps']} steps, {provenance['n_toys']} toys.",
        f"- flavio {provenance['flavio_version']}, "
        f"wilson {provenance['wilson_version']}.",
        f"- Input `data/p5p_observables.csv` sha256 "
        f"`{provenance['data_sha256'][:16]}…`",
        f"- Theory covariance included: "
        f"{provenance['theory_covariance_included']}; experimental "
        f"correlations included: "
        f"{provenance['experimental_correlations_included']}.",
        "",
        "_This section is generated by `scripts/update_readme.py`. "
        "Run `make readme` to refresh it._",
        "",
        END,
    ]
    return "\n".join(lines)


def main() -> None:
    text = README.read_text()
    block = render()

    if START in text and END in text:
        head, rest = text.split(START, 1)
        _, tail = rest.split(END, 1)
        text = head + block + tail
    else:
        text = text.rstrip() + "\n\n## Results\n\n" + block + "\n"

    README.write_text(text)
    print(f"Updated the generated block in {README.name}.")


if __name__ == "__main__":
    main()
